### ISSUE TITLE
Redhat7 has a five-fold increase in bandwidth compared to Redhat6

### ISSUE THREAD

**Issue by wang332127858** [TurboVNC/buildscripts#2]
versions 2.2.5
Redhat7 has a five-fold increase in bandwidth compared to Redhat6

**Comment by dcommander** [comment]
Please explain what you mean and how to reproduce the problem.

**Comment by wang332127858** [comment]
> 请解释您的意思以及如何重现该问题。
Repeat steps
vnc version：2.2.5
OS：Linux root 2.6.32-431.el6.x86_64，Linux root 3.10.0-1062.12.1.el7.x86_64
Play the same video, Bandwidth of the client has been detected, The bandwidth of rhel7.6  is five times that of rhel6

**Comment by wang332127858** [comment]
> Please explain what you mean and how to reproduce the problem.

Repeat steps
vnc version：2.2.5
OS：Linux root 2.6.32-431.el6.x86_64，Linux root 3.10.0-1062.12.1.el7.x86_64
Play the same video, Bandwidth of the client has been detected, The bandwidth of rhel7.6 is five times that of rhel6

**Comment by wang332127858** [comment]
> Please explain what you mean and how to reproduce the problem.

Repeat steps
vnc version：2.2.5
OS：Linux root 2.6.32-431.el6.x86_64，Linux root 3.10.0-1062.12.1.el7.x86_64
desktop:xfce4
Play the same video, Bandwidth of the client has been detected, The bandwidth of rhel7.6 is five times that of rhel6

**Comment by dcommander** [comment]
Play the same video using what software? What do you mean by “bandwidth of the client has been detected”? Please provide complete and exact reproduction steps if you want me to investigate this. Otherwise, I can only conclude that your inability to describe the problem may also reflect an inability to diagnose it, which casts doubt on whether it is an actual problem.

**Comment by wang332127858** [comment]
> Play the same video using what software? What do you mean by “bandwidth of the client has been detected”? Please provide complete and exact reproduction steps if you want me to investigate this. Otherwise, I can only conclude that your inability to describe the problem may also reflect an inability to diagnose it, which casts doubt on whether it is an actual problem.

More detailed steps
1.Connect to the rhel6 server desktop using the Viewer
2.You can run a glxgears on terminal or nothing to do
3.Check the traffic of Viewer in Explorer（task manageer）
4.Connect to the rhel7 and Repeat the above steps
5.Compare the traffic of two Viewer,RHel7 is significantly higher than RHel6，I suspect that the picture captured by RHel7  is bigger

**Comment by wang332127858** [comment]
After repeated testing, I confirmed that it is a performance bug, please confirm.

**Comment by dcommander** [comment]
Try enabling interframe comparison in the TurboVNC Viewer (or starting the TurboVNC Server with `-interframe`.)  That seems to work around the issue for me.  I'm not sure of the cause, but it seems to be related to Mesa.  I don't observe the issue with other types of applications, including OpenGL applications running with VirtualGL or actual video players.

In the future, please post such issues under the TurboVNC issue tracker:
https://github.com/TurboVNC/turbovnc/issues
This issue tracker is used only for the official TurboVNC build scripts, and the reported issue is unrelated to those.

**Comment by dcommander** [comment]
Note: I also observe the issue with the TigerVNC Server.
