### ISSUE TITLE
Installation failing

### ISSUE THREAD

**Issue by drozdi70** [TurboVNC/buildscripts#3]
Hi
-- CMAKE_INSTALL_DATAROOTDIR =  (/opt/TurboVNC)
-- CMAKE_INSTALL_DATADIR =  (/opt/TurboVNC)
-- CMAKE_INSTALL_DOCDIR = doc (/opt/TurboVNC/doc)
-- CMAKE_INSTALL_MANDIR = man (/opt/TurboVNC/man)
-- CMAKE_INSTALL_SYSCONFDIR = /etc
-- 64-bit build (arm64)
CMake Error at cmakescripts/FindTurboJPEG.cmake:32 (message):
  Could not find turbojpeg.h in /opt/libjpeg-turbo/include.  If it is
  installed in a different place, then set TJPEG_INCLUDE_DIR accordingly.
Call Stack (most recent call first):
  CMakeLists.txt:181 (include)

OS info:
orangepi@orangepi5:~/work$ uname -a
Linux orangepi5 5.10.110-rockchip-rk3588 #23.02.2 SMP Fri Feb 17 23:59:20 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
orangepi@orangepi5:~/work$ uname -r
5.10.110-rockchip-rk3588
orangepi@orangepi5:~/work$ more /etc/*release*
::::::::::::::
/etc/armbian-image-release
::::::::::::::
# PLEASE DO NOT EDIT THIS FILE
BOARD=orangepi5
BOARD_NAME="Orange Pi 5"
BOARDFAMILY=rockchip-rk3588
BUILD_REPOSITORY_URL=https://github.com/armbian/build
BUILD_REPOSITORY_COMMIT=1a8daf0
VERSION=23.02.2
LINUXFAMILY=rockchip-rk3588
ARCH=arm64
IMAGE_TYPE=stable
BOARD_TYPE=conf
INITRD_ARCH=arm64
KERNEL_IMAGE_TYPE=stable
IMAGE_UUID=7dac041e-a3bb-4354-856f-288fa32eddf4
::::::::::::::
/etc/armbian-release
::::::::::::::
# PLEASE DO NOT EDIT THIS FILE
BOARD=orangepi5
BOARD_NAME="Orange Pi 5"
BOARDFAMILY=rockchip-rk3588
BUILD_REPOSITORY_URL=https://github.com/armbian/build
BUILD_REPOSITORY_COMMIT=1a8daf0
VERSION=23.02.2
LINUXFAMILY=rockchip-rk3588
ARCH=arm64
IMAGE_TYPE=stable
BOARD_TYPE=conf
INITRD_ARCH=arm64
KERNEL_IMAGE_TYPE=stable
BRANCH=legacy
::::::::::::::
/etc/lsb-release
::::::::::::::
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
::::::::::::::
/etc/os-release
::::::::::::::
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

Kindly

**Comment by dcommander** [comment]
Also, do not post issues under this repository unless they are specifically related to the scripts in this repository.

**Comment by drozdi70** [comment]
Histill ***@***.***:~/work/buildscripts$ ./buildvncChecking out TurboVNC from main ...Cloning into 'vnc'...remote: Enumerating objects: 2198, done.remote: Counting objects: 100% (2198/2198), done.remote: Compressing objects: 100% (1880/1880), done.remote: Total 2198 (delta 535), reused 692 (delta 284), pack-reused 0Receiving objects: 100% (2198/2198), 9.16 MiB | 667.00 KiB/s, done.Resolving deltas: 100% (535/535), done.Creating source tarball and SRPM .../tmp/vncbuild.JlHbru/vnc.pristine /tmp/vncbuild.JlHbru/tmp/vncbuild.JlHbru/tmp/vncbuild.JlHbru/vnc /tmp/vncbuild.JlHbruOpenJDK 11.0.18 already installed.OpenJDK 11.0.18 already installed.-- TurboVNC Helper (JNI) enabled (TVNC_BUILDHELPER = 1)-- TurboVNC Viewer (Java) enabled (TVNC_BUILDVIEWER = 1)-- TurboVNC Server enabled (TVNC_BUILDSERVER = 1)-- The C compiler identification is GNU 11.3.0-- Detecting C compiler ABI info-- Detecting C compiler ABI info - done-- Check for working C compiler: /usr/bin/cc - skipped-- Detecting C compile features-- Detecting C compile features - done-- CMAKE_BUILD_TYPE = RelWithDebInfo-- VERSION = 3.0.4, BUILD = 20230414-- CMAKE_INSTALL_PREFIX = /opt/TurboVNC-- CMAKE_INSTALL_BINDIR = bin (/opt/TurboVNC/bin)-- CMAKE_INSTALL_DATAROOTDIR =&nbsp; (/opt/TurboVNC)-- CMAKE_INSTALL_DATADIR =&nbsp; (/opt/TurboVNC)-- CMAKE_INSTALL_DOCDIR = doc (/opt/TurboVNC/doc)-- CMAKE_INSTALL_MANDIR = man (/opt/TurboVNC/man)-- CMAKE_INSTALL_SYSCONFDIR = /etc-- 64-bit build (arm64)-- TJPEG_INCLUDE_DIR = /opt/libjpeg-turbo/include-- Performing Test TURBOJPEG_WORKS-- Performing Test TURBOJPEG_WORKS - Success-- TJPEG_LIBRARY = /opt/libjpeg-turbo/lib64/libturbojpeg.aCMake Error at /usr/share/cmake-3.22/Modules/FindJava.cmake:171 (message):&nbsp; Error executing java -versionCall Stack (most recent call first):&nbsp; java/CMakeLists.txt:1 (find_package)-- Configuring incomplete, errors occurred!See also ***@***.***:~/work/buildscripts$ java -versionopenjdk version "11.0.18" 2023-01-17OpenJDK Runtime Environment (build 11.0.18+10-post-Ubuntu-0ubuntu122.04)OpenJDK 64-Bit Server VM (build 11.0.18+10-post-Ubuntu-0ubuntu122.04, mixed mode)Temat: Re: [TurboVNC/buildscripts] Installation failing (Issue #3)Data: 2023-04-13 22:31Nadawca: "DRC" ***@***.***&gt;Adresat: "TurboVNC/buildscripts" ***@***.***&gt;; DW: "drozdi70" ***@***.***&gt;; "Author" ***@***.***&gt;; 

Install the amd64 .deb package from an official libjpeg-turbo release and try again.

**Comment by drozdi70** [comment]
and I fixed some other issues but finally installation ends with:-- Build files have been written to: /tmp/vncbuild.0o0fg1/vncBuilt target dist/tmp/vncbuild.0o0fg1/tmp/vncbuild.0o0fg1/vnc /tmp/vncbuild.0o0fg1Built target distpkgscripts/makesrpm: 45: rpmbuild: not foundmake[3]: *** [CMakeFiles/srpm.dir/build.make:70: CMakeFiles/srpm] Error 127make[2]: *** [CMakeFiles/Makefile2:1122: CMakeFiles/srpm.dir/all] Error 2make[1]: *** [CMakeFiles/Makefile2:1129: CMakeFiles/srpm.dir/rule] Error 2make: *** [Makefile:182: srpm] Error 2on my OS Ubuntu/Armbain rather normal....Temat: Re: [TurboVNC/buildscripts] Installation failing (Issue #3)Data: 2023-04-13 22:31Nadawca: "DRC" ***@***.***&gt;Adresat: "TurboVNC/buildscripts" ***@***.***&gt;; DW: "drozdi70" ***@***.***&gt;; "Author" ***@***.***&gt;; 

Install the amd64 .deb package from an official libjpeg-turbo release and try again.

**Comment by dcommander** [comment]
No, I didn't say use the scripts in this repository. These scripts are designed for our internal use when building official binaries. What I said was post issues such as these in the main repository. The way to solve your problem is to install the appropriate official libjpeg-turbo package for your architecture and then build TurboVNC the way you first tried to build it.
